### ISSUE TITLE
Nuget package does not build for .net 4.5

### ISSUE THREAD

**Issue by ganeshvelanki** [SparkPost/csharp-sparkpost#13]
when i am trying to build my solution, i get this 

warning MSB3274: The primary reference "SparkPost" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. 

which is causing build to fail, i see that there is a release for 4.5, but is it updated in nuget repo?

**Comment by darrencauthon** [comment]
Have you tried upgrading to the latest version?  1.0.2 or greater should have this resolved.

**Comment by ganeshvelanki** [comment]
i tried both 1.0.2 and 1.0.1 but no luck.. :(, the msbuild says above error as mentioned.

**Comment by darrencauthon** [comment]
I believe this was fixed with 1.0.1.  I just released 1.0.3 to fix something else.  I just pulled that version for my final test and I seems to work fine on 4.5 for me:

![screenshot_032116_010021_pm](https://cloud.githubusercontent.com/assets/148768/13928729/df0da6d6-ef64-11e5-9167-92f405758636.jpg)

**Comment by ganeshvelanki** [comment]
Its fixed with 1.0.3 nuget package, thanks for the effort
